--- #YAML:1.0
name: Class-DBI-GraphEasy
version: 0.07
author:
  - Xufeng Liang <danny@scm.uws.edu.au>
abstract: use Graph::Easy to graph Class::DBI classes automatically
license: perl
requires:
  Graph::Easy: 0
  Class::DBI: 0
  Class::ISA: 0
  Test::More: 0
provides:
  Class::DBI::GraphEasy:
    file: lib/Class/DBI/GraphEasy.pm
    version: 0.07
generated_by: Module::Build version 0.2609
